### ISSUE TITLE
Third party license file generator does not find requirements.txt

### ISSUE THREAD

**Issue by fhg-isi** [fraunhofer-isi/micat#16]
https://github.com/fraunhofer-isi/micat/actions/runs/8786855543/job/24110673522

**Comment by fhg-isi** [comment]
I replaced the hard coded path to python with `$(which python3)`.

The python version is currently set to 3.11. We could automat that selection, too:

```
- name: setup python
  uses: actions/setup-python@v5
  with:
    python-version: auto  # 3.11
```

However, I keep 3.11 for the time beeing. 

@Tyrdall
